ALTER SERVER ROLE [sysadmin] ADD MEMBER [DESKTOP-U1A6SP5\AEPIS01];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\SQLWriter];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\Winmgmt];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT Service\MSSQLSERVER];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\SQLSERVERAGENT];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [l_certSignSmDetach];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [USULPII];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [ULPII];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [USUPII];


GO
ALTER SERVER ROLE [dbcreator] ADD MEMBER [USULPII];


GO
ALTER SERVER ROLE [dbcreator] ADD MEMBER [ULPII];


GO
ALTER SERVER ROLE [dbcreator] ADD MEMBER [USUPII];

